import type { Language } from "@/types/language";

export const weddingContent = {
  names: {
    ko: "구은성 | 김예은",
    en: "Gu Eunseong | Kim Yeeun",
  },
  parents: {
    ko: {
      groom: "구지홍 · 황미선의 장남 구은성",
      bride: "김광일 · 최경림의 딸 김예은",
    },
    en: {
      groom: "Eldest son of Gu Jihong and Hwang Miseon",
      bride: "Daughter of Kim Gwangil and Choi Gyeongrim",
    },
  },
  venue: {
    name: "꽃재교회 2층 대예배실",
    address: "기독교대한감리회 꽃재교회 2층 대예배실,\n마장로 164(1070-5)",
  },
  date: {
    iso: "2026-06-06T12:00:00+09:00",
    koFull: "2026년 6월 6일 토요일 낮 12시",
    enFull: "Saturday, June 6, 2026 at 12:00 PM",
  },
} as const;

export const invitationCopy = {
  ko: {
    badge: "Wedding Invitation",
    nav: {
      language: "ENG",
      copyLink: "링크 복사",
      copyAddress: "주소 복사",
      copied: "복사되었습니다",
      kakaoShare: "카카오 공유",
      kakaoShareSoon: "카카오 공유는 추후 연결됩니다",
      addCalendar: "캘린더에 추가",
      downloadIcs: "ICS 다운로드",
    },
    hero: {
      title: "결혼합니다",
      subtitle: "서로에게 가장 귀한 선물이 될 두 사람의 시작",
      dateLine: weddingContent.date.koFull,
      venueLine: weddingContent.venue.name,
    },
    invitation: {
      heading: "초대합니다",
      body: [
        "서로 다른 나라에서 살아온 두 사람이 사랑이라는 가장 큰 선물로 하나가 되었습니다.",
        "이제 소중한 분들 앞에서 평생 서로에게 가장 귀한 선물이 되겠다고 약속하려 합니다.",
        "두 사람이 한 가정을 이루는 이 순간에 함께하시어 축복해주시면 감사하겠습니다.",
      ],
    },
    information: {
      heading: "예식 안내",
      groomLabel: "신랑",
      brideLabel: "신부",
      parentHeading: "혼주",
      dateHeading: "일시",
      venueHeading: "장소",
    },
    calendar: {
      heading: "Wedding Calendar",
      caption: "2026년 6월 6일 토요일",
      ddayPrefix: "예식까지 ",
      ddaySuffix: "일",
      ddayDone: "오늘은 예식 당일입니다",
      ddayPassed: "소중한 예식이 잘 마무리되었습니다",
    },
    venue: {
      heading: "오시는 길",
      subheading: "꽃재교회 2층 대예배실",
      addressLabel: "주소",
      naver: "네이버 지도",
      kakao: "카카오맵",
      mapHint: "마장로 164 · 2층 대예배실",
    },
    rsvp: {
      heading: "참석 의사 전달",
      description: "예식 준비를 위해 참석 여부를 알려주시면 감사하겠습니다.",
      openModal: "작성하기",
      closeModal: "닫기",
      name: "성함",
      phone: "연락처",
      side: "신랑측 / 신부측",
      attendance: "참석 여부",
      attendeeCount: "참석 인원",
      meal: "식사 참석",
      message: "전하고 싶은 말 (선택)",
      sideOptions: {
        groom: "신랑측",
        bride: "신부측",
      },
      attendanceOptions: {
        attending: "참석",
        notAttending: "불참",
      },
      mealOptions: {
        yes: "예",
        no: "아니오",
      },
      validation: {
        nameRequired: "성함을 입력해주세요.",
        phoneRequired: "연락처를 입력해주세요.",
        phoneInvalid: "연락처 형식을 다시 확인해주세요.",
        attendeeCountRequired: "참석 인원을 1명 이상 입력해주세요.",
      },
      submit: "전송하기",
      submitting: "전송 중...",
      success: "참석 의사가 전달되었습니다. 감사합니다.",
      error: "전송에 실패했습니다. 잠시 후 다시 시도해주세요.",
    },
    gallery: {
      heading: "Gallery",
      description: "두 사람의 순간을 담은 사진들을 천천히 감상해보세요.",
      viewAll: "전체 갤러리 보기",
      openLabel: "이미지 보기",
      close: "닫기",
      next: "다음",
      prev: "이전",
    },
    upload: {
      heading: "하객 사진 업로드",
      description: "예식 당일의 소중한 장면을 공유해주세요.",
      openModal: "사진 업로드하기",
      closeModal: "닫기",
      uploaderName: "업로드하는 분 성함 (선택)",
      fileInput: "사진 선택 (여러 장 가능)",
      helper: "지원 형식: JPG, PNG, WEBP",
      limitNote: "최대 {count}장 · 파일당 최대 {sizeMb}MB",
      privacyNotice: "업로드된 사진은 바로 공개되지 않으며 승인 전까지 비공개로 보관됩니다.",
      submit: "업로드 시작",
      uploading: "업로드 중...",
      done: "사진이 접수되었습니다. 현재는 비공개 상태이며 승인 후 검토됩니다.",
      failed: "일부 파일 업로드에 실패했습니다. 다시 시도해주세요.",
      retry: "재시도",
      remove: "제거",
      tooManyFiles: "한 번에 최대 {count}장까지 업로드할 수 있습니다.",
      invalidType: "{name} 파일은 JPG, PNG, WEBP 형식만 업로드할 수 있습니다.",
      tooLarge: "{name} 파일은 {sizeMb}MB 이하만 업로드할 수 있습니다.",
      missingTarget: "업로드 세션을 준비하지 못했습니다. 다시 시도해주세요.",
      finalizeFailed: "업로드는 완료되었지만 저장 확인에 실패했습니다. 잠시 후 다시 시도해주세요.",
    },
    account: {
      heading: "마음 전하는 곳",
      intro: "참석이 어려우신 분들을 위해 \n계좌번호를 안내해 드립니다.\n너그러운 마음으로 양해 부탁드립니다.",
      groomSide: "신랑측",
      brideSide: "신부측",
      openModal: "마음 전하기",
      closeModal: "닫기",
      copy: "복사",
      copied: "복사됨",
    },
    footer: {
      thanks:
        "부부의 연을 맺는 소중한 날\n귀한 걸음으로 함께해주셔서 진심으로 감사합니다.\n서로를 사랑하고 섬기며 예쁘게 살겠습니다.",
      thanks2: "",
      signature: "구은성 · 김예은 드림",
    },
  },
  en: {
    badge: "Wedding Invitation",
    nav: {
      language: "한국어",
      copyLink: "Copy Link",
      copyAddress: "Copy Address",
      copied: "Copied",
      kakaoShare: "Kakao Share",
      kakaoShareSoon: "Kakao share placeholder",
      addCalendar: "Add to Calendar",
      downloadIcs: "Download ICS",
    },
    hero: {
      title: "We Are Getting Married",
      subtitle: "A tender beginning for two hearts becoming one gift",
      dateLine: weddingContent.date.enFull,
      venueLine: weddingContent.venue.name,
    },
    invitation: {
      heading: "You are invited",
      body: [
        "Two people from two different lands have received the greatest gift.",
        "Now they promise to be each other's gift forever.",
        "We invite those we love to bless us as we unite our hearts as one.",
      ],
    },
    information: {
      heading: "Wedding Details",
      groomLabel: "Groom",
      brideLabel: "Bride",
      parentHeading: "Families",
      dateHeading: "Date & Time",
      venueHeading: "Venue",
    },
    calendar: {
      heading: "Wedding Calendar",
      caption: "Saturday, June 6, 2026",
      ddayPrefix: "D-",
      ddaySuffix: "",
      ddayDone: "Today is our wedding day",
      ddayPassed: "Our wedding day has gracefully passed",
    },
    venue: {
      heading: "Location",
      subheading: "Kkotjae Church 2F Grand Chapel",
      addressLabel: "Address",
      naver: "Naver Map",
      kakao: "Kakao Map",
      mapHint: "164 Majang-ro · 2F Grand Chapel",
    },
    rsvp: {
      heading: "RSVP",
      description: "Please let us know your attendance to help us prepare with care.",
      openModal: "Write RSVP",
      closeModal: "Close",
      name: "Name",
      phone: "Phone number",
      side: "Groom side / Bride side",
      attendance: "Attendance",
      attendeeCount: "Number of attendees",
      meal: "Meal attendance",
      message: "Optional message",
      sideOptions: {
        groom: "Groom side",
        bride: "Bride side",
      },
      attendanceOptions: {
        attending: "Attending",
        notAttending: "Not attending",
      },
      mealOptions: {
        yes: "Yes",
        no: "No",
      },
      validation: {
        nameRequired: "Please enter your name.",
        phoneRequired: "Please enter your phone number.",
        phoneInvalid: "Please check the phone number format.",
        attendeeCountRequired: "Please enter at least one attendee.",
      },
      submit: "Submit RSVP",
      submitting: "Submitting...",
      success: "Your RSVP has been sent. Thank you.",
      error: "Submission failed. Please try again shortly.",
    },
    gallery: {
      heading: "Gallery",
      description: "A collection of moments that led us to this day.",
      viewAll: "View Full Gallery",
      openLabel: "Open image",
      close: "Close",
      next: "Next",
      prev: "Previous",
    },
    upload: {
      heading: "Guest Photo Upload",
      description: "Share your wedding-day photos.",
      openModal: "Open Upload Form",
      closeModal: "Close",
      uploaderName: "Your name (optional)",
      fileInput: "Choose photos (multiple files)",
      helper: "Supported formats: JPG, PNG, WEBP",
      limitNote: "Up to {count} files · {sizeMb}MB each",
      privacyNotice: "Uploaded photos stay private until they are manually reviewed and approved.",
      submit: "Start upload",
      uploading: "Uploading...",
      done: "Your photos have been received. They stay private until approval is complete.",
      failed: "Some uploads failed. Please retry.",
      retry: "Retry",
      remove: "Remove",
      tooManyFiles: "You can upload up to {count} files at a time.",
      invalidType: "{name} must be a JPG, PNG, or WEBP image.",
      tooLarge: "{name} must be {sizeMb}MB or smaller.",
      missingTarget: "The upload session could not be prepared. Please retry.",
      finalizeFailed: "The files uploaded, but the confirmation step failed. Please retry shortly.",
    },
    account: {
      heading: "Account",
      intro: "For guests who cannot attend in person, we share our account details below.",
      groomSide: "Groom Side",
      brideSide: "Bride Side",
      openModal: "Send Gift",
      closeModal: "Close",
      copy: "Copy",
      copied: "Copied",
    },
    footer: {
      thanks: "Thank you for celebrating this precious moment with us.",
      signature: "With love, Gu Eunseong & Kim Yeeun",
    },
  },
} as const;

export type InvitationCopy = (typeof invitationCopy)[Language];
